module: MaterialMotionDirectManipulationFamily
module_version: 1.0.0
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - MaterialMotionDirectManipulationFamily.xcworkspace
  - -scheme
  - MaterialMotionDirectManipulationFamily
github_url: https://github.com/material-motion/material-motion-family-direct-manipulation-swift
github_file_prefix: https://github.com/material-motion/material-motion-family-direct-manipulation-swift/tree/v1.0.0
